#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Joshua Kimsey
"""Build the self-contained LibreWXR example pages.

Reads examples/src/viewer.css and viewer-core.js plus each per-library shell
(leaflet.html.js / maplibre.html.js / hero.html.js / widget.html.js), inlines
the shared assets at the placeholder tokens, and writes single-file pages to
examples/:

    /*__VIEWER_CSS__*/   -> viewer.css contents (token lives inside a <style>)
    //__VIEWER_CORE__    -> viewer-core.js contents (token lives inside a <script>)

The CSS token is required for every shell; the core token is optional and is
simply skipped when absent - the widget shell is deliberately standalone and
does not use the shared 1900-line map engine.

With --site it additionally writes SEO-enriched variants to
librewxr-site/examples/ for whichever pages have SITE_PAGES metadata (leaflet,
maplibre, widget): the API base pinned to https://api.librewxr.net, the
#lv-source selector markup removed when present, and the site's meta head
(description/canonical/OG/twitter/favicon) injected - the same pattern the
hand-maintained site examples already use.

--site also regenerates the shared-engine hero embedded in the marketing
front page librewxr-site/index.html. Three regions of that page live between
marker comments (__HERO_MARKUP__, __HERO_SCRIPT__, __HERO_CSS__) and are
rebuilt from the same hero.html.js shell that produces examples/hero.html:

  * markup - the .radar-viewer/.radar-container block holding the new hero
    structure (#lv-map, preload indicator, locate button, error overlay,
    replayer with #lv-play/#lv-scrubber-track/#lv-scrubber-ticks/#lv-timestamp)
  * script - viewer-core.js inlined, plus the LeafletAdapter and the locked
    LibreWXR.createViewer(...) hero config with the API base pinned to
    https://api.librewxr.net
  * css    - the full viewer.css inlined, plus hero-embedding overrides
    (fixed map height 500/400/320px and a normal scrolling body)

The regeneration is idempotent: the generated content never contains the
markers, so repeated --site runs replace exactly the same spans. Do not
hand-edit between the markers.

Stdlib only; no third-party dependencies.
"""

import argparse
import datetime
import os
import subprocess
import sys

SRC_DIR = os.path.dirname(os.path.abspath(__file__))
EXAMPLES_DIR = os.path.dirname(SRC_DIR)
PROJECT_ROOT = os.path.dirname(EXAMPLES_DIR)
SITE_EXAMPLES_DIR = os.path.join(PROJECT_ROOT, "librewxr-site", "examples")

GENERATED_COMMENT = (
    "<!-- SPDX-License-Identifier: MIT -->\n"
    "<!-- The examples in this directory are licensed under the MIT License. -->\n"
    "<!-- See LICENSE-examples file for the full license text. -->\n"
    "<!-- You are free to copy, modify, and use these files in your own projects under MIT terms. -->\n"
    "<!-- GENERATED by examples/src/build.py - do not edit directly -->"
)

CSS_TOKEN = "/*__VIEWER_CSS__*/"
CORE_TOKEN = "//__VIEWER_CORE__"

# --site rewrites
API_FIXED_NULL = "var LVR_API_FIXED = null;"
API_FIXED_PIN = "var LVR_API_FIXED = 'https://api.librewxr.net';"
SOURCE_BLOCK_START = "<!-- #lv-source block"
SOURCE_BLOCK_END = "<!-- /#lv-source -->"
VIEWPORT_META = '<meta content="width=device-width, initial-scale=1.0" name="viewport">'

# Per-page site metadata (mirrors the existing librewxr-site/examples heads).
SITE_PAGES = {
    "leaflet": {
        "page": "leaflet",
        "title": "LibreWXR - Leaflet Example",
        "description": (
            "Live LibreWXR weather radar tiles rendered with Leaflet. "
            "Interactive multi-region radar with playback controls."
        ),
        "twitter_description": (
            "Live weather radar tiles rendered with Leaflet, powered by the LibreWXR API."
        ),
    },
    "maplibre": {
        "page": "maplibre",
        "title": "LibreWXR - MapLibre Example",
        "description": (
            "Live LibreWXR weather radar tiles rendered with MapLibre GL JS. "
            "WebGL-accelerated multi-region radar with playback controls."
        ),
        "twitter_description": (
            "WebGL-accelerated weather radar tiles rendered with MapLibre GL JS, "
            "powered by the LibreWXR API."
        ),
    },
    "widget": {
        "page": "widget",
        "title": "LibreWXR - Radar Widget Example",
        "description": (
            "A drop-in animated radar image for any location, rendered with the "
            "LibreWXR lat/lon point-tile API. No map library required."
        ),
        "twitter_description": (
            "A self-contained animated radar widget for any location, powered "
            "by the LibreWXR lat/lon-centered point-tile API."
        ),
    },
}

SITE_META = """    <meta name="description" content="{description}">
    <meta name="author" content="Joshua Kimsey">
    <meta name="theme-color" content="#0f1117">
    <link rel="canonical" href="https://librewxr.net/examples/{page}.html">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="LibreWXR">
    <meta property="og:locale" content="en_US">
    <meta property="og:url" content="https://librewxr.net/examples/{page}.html">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description}">
    <meta property="og:image" content="https://librewxr.net/LibreWXR-Logo.png">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{title}">
    <meta name="twitter:description" content="{twitter_description}">
    <meta name="twitter:image" content="https://librewxr.net/LibreWXR-Logo.png">
    <link rel="icon" type="image/png" href="../LibreWXR-Logo.png">
    <link rel="apple-touch-icon" href="../LibreWXR-Logo.png">"""

# --site marketing front-page hero regeneration (librewxr-site/index.html).
# The three hero regions of the page live between these marker comments;
# build.py --site replaces the text between each pair (markers stay in place,
# so the operation is idempotent).
INDEX_PATH = os.path.join(PROJECT_ROOT, "librewxr-site", "index.html")
HERO_SHELL = "hero.html.js"
BODY_TAG = '<body data-theme="dark">'

HERO_MARKUP_START = "<!-- __HERO_MARKUP_START__ -->"
HERO_MARKUP_END = "<!-- __HERO_MARKUP_END__ -->"
HERO_SCRIPT_START = "<!-- __HERO_SCRIPT_START__ -->"
HERO_SCRIPT_END = "<!-- __HERO_SCRIPT_END__ -->"
HERO_CSS_START = "/* __HERO_CSS_START__ */"
HERO_CSS_END = "/* __HERO_CSS_END__ */"

HERO_OVERRIDE_CSS = """/* === SITE HERO EMBEDDING (marketing front page) ===
   viewer.css above is written for full-page demo shells: it makes <body> a
   non-scrolling flex column filling the viewport. The marketing page is a
   normal scrolling document with its own header/content/footer, so neutralize
   those base rules and pin the embedded map to a fixed height instead of the
   full-page flex:1 the viewer.css uses. */
body {
    overflow: visible;
    height: auto;
    display: block;
}

.radar-viewer #lv-map {
    height: 500px;
    flex: none;
}

@media (max-width: 768px) {
    .radar-viewer #lv-map {
        height: 400px;
    }
}

@media (max-width: 480px) {
    .radar-viewer #lv-map {
        height: 320px;
    }
}"""


def read_file(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def write_file(path, text):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def git_short_hash():
    """Short HEAD hash for the build marker; 'unknown' outside a git repo."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=5,
        )
        if out.returncode == 0:
            return out.stdout.strip() or "unknown"
    except Exception:
        pass  # no git, or git unavailable: fall back to 'unknown'
    return "unknown"


def build_marker():
    """Build-stamp comment, emitted right after the GENERATED line."""
    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return "<!-- librewxr-examples build: %s git:%s -->" % (ts, git_short_hash())


def inline_assets(html):
    """Replace the placeholder tokens with the shared CSS and core JS.

    The CSS token is required for every shell. The core token is optional:
    shells without it (the standalone widget page) simply skip core inlining.
    """
    css = read_file(os.path.join(SRC_DIR, "viewer.css"))
    if CSS_TOKEN not in html:
        raise SystemExit("error: shell missing CSS token %r" % CSS_TOKEN)
    html = html.replace(CSS_TOKEN, css)
    if CORE_TOKEN in html:
        core = read_file(os.path.join(SRC_DIR, "viewer-core.js"))
        html = html.replace(CORE_TOKEN, core)
    return html


def make_site_variant(html, meta):
    """Pin the API base, drop the source selector, inject the site meta head."""
    if API_FIXED_NULL not in html:
        raise SystemExit("error: --site build needs %r in the shell" % API_FIXED_NULL)
    html = html.replace(API_FIXED_NULL, API_FIXED_PIN)

    # Remove the #lv-source selector markup, markers inclusive, whole lines.
    # Shells without the selector (hero, widget) keep their markup untouched.
    start = html.find(SOURCE_BLOCK_START)
    end = html.find(SOURCE_BLOCK_END)
    if start != -1 and end != -1:
        line_start = html.rfind("\n", 0, start) + 1
        line_end = html.find("\n", end)
        if line_end != -1:
            html = html[:line_start] + html[line_end + 1 :]

    html = html.replace("<html>", '<html lang="en">', 1)

    if VIEWPORT_META not in html:
        raise SystemExit("error: viewport meta not found for --site")
    html = html.replace(VIEWPORT_META, VIEWPORT_META + "\n" + meta, 1)
    return html


def replace_region(html, start_marker, end_marker, content):
    """Replace the text between two marker comments with `content`.

    Markers are kept in place, so the operation is idempotent. Fails loudly
    if a marker went missing (the hero regions of index.html must not be
    hand-edited).
    """
    try:
        start = html.index(start_marker) + len(start_marker)
        end = html.index(end_marker, start)
    except ValueError:
        raise SystemExit(
            "error: %r and %r markers not found in librewxr-site/index.html "
            "- the shared-engine hero markers were removed or renamed"
            % (start_marker, end_marker)
        )
    return html[:start] + "\n" + content + "\n" + html[end:]


def build_hero_markup():
    """The hero body markup from hero.html.js (map div + replayer), wrapped in
    the marketing page's .radar-viewer/.radar-container chrome."""
    shell = read_file(os.path.join(SRC_DIR, HERO_SHELL))
    start = shell.index(BODY_TAG) + len(BODY_TAG)
    end = shell.index("<script>", start)
    inner = shell[start:end].strip("\n")
    indented = "\n".join(
        ("    " + line) if line.strip() else line for line in inner.splitlines()
    )
    return (
        "<!-- Radar Viewer - shared-engine hero (regenerated by "
        "examples/src/build.py --site) -->\n"
        '<div class="radar-viewer">\n'
        '    <div class="radar-container">\n'
        + indented
        + "\n"
        "    </div>\n"
        "</div>"
    )


def build_hero_script():
    """viewer-core.js + the hero LeafletAdapter + locked createViewer config
    (API base pinned to the public endpoint), sourced from hero.html.js."""
    core = read_file(os.path.join(SRC_DIR, "viewer-core.js"))
    shell = read_file(os.path.join(SRC_DIR, HERO_SHELL))
    core_pos = shell.index(CORE_TOKEN)
    core_close = shell.index("</script>", core_pos)
    open_pos = shell.index("<script>", core_close)
    close_pos = shell.index("</script>", open_pos)
    tail = shell[open_pos : close_pos + len("</script>")]
    if API_FIXED_NULL not in tail and API_FIXED_PIN not in tail:
        raise SystemExit("error: hero shell needs LVR_API_FIXED marker for the site index hero")
    if API_FIXED_NULL in tail:
        tail = tail.replace(API_FIXED_NULL, API_FIXED_PIN)
    return (
        "<!-- Radar hero script - shared engine (regenerated by "
        "examples/src/build.py --site) -->\n"
        "<script>\n" + core + "\n</script>\n\n" + tail
    )


def build_hero_css():
    """The full viewer.css plus the marketing-page embedding overrides."""
    css = read_file(os.path.join(SRC_DIR, "viewer.css"))
    return (
        "/* Shared-engine hero CSS - viewer.css plus page overrides "
        "(regenerated by examples/src/build.py --site) */\n"
        + css.rstrip("\n")
        + "\n\n"
        + HERO_OVERRIDE_CSS.rstrip("\n")
    )


def rebuild_site_index_hero():
    """Regenerate the three shared-engine hero regions of the marketing page."""
    path = INDEX_PATH
    html = read_file(path)
    html = replace_region(html, HERO_MARKUP_START, HERO_MARKUP_END, build_hero_markup())
    html = replace_region(html, HERO_SCRIPT_START, HERO_SCRIPT_END, build_hero_script())
    html = replace_region(html, HERO_CSS_START, HERO_CSS_END, build_hero_css())
    write_file(path, html)
    print(
        "updated %s (%d bytes, --site)"
        % (os.path.join("librewxr-site", "index.html"), os.path.getsize(path))
    )


def build_pages(args):
    marker = build_marker()  # one timestamp/hash per run, stamped into every page
    pages = [
        ("leaflet.html.js", "leaflet.html"),
        ("maplibre.html.js", "maplibre.html"),
        ("hero.html.js", "hero.html"),
        ("widget.html.js", "widget.html"),
    ]
    for shell, out in pages:
        html = GENERATED_COMMENT + "\n" + marker + "\n" + inline_assets(read_file(os.path.join(SRC_DIR, shell)))
        dest = os.path.join(EXAMPLES_DIR, out)
        write_file(dest, html)
        print("wrote %s (%d bytes)" % (os.path.join("examples", out), os.path.getsize(dest)))

    if args.site:
        if not os.path.isdir(os.path.dirname(SITE_EXAMPLES_DIR)):
            print("notice: librewxr-site/ not found, skipping --site output")
            return
        for shell, out in pages:
            key = out[: -len(".html")]  # 'leaflet' / 'maplibre' / 'widget' / 'hero'
            if key not in SITE_PAGES:
                continue  # no site metadata for this page (hero)
            html = GENERATED_COMMENT + "\n" + marker + "\n" + inline_assets(read_file(os.path.join(SRC_DIR, shell)))
            html = make_site_variant(html, SITE_META.format(**SITE_PAGES[key]))
            dest = os.path.join(SITE_EXAMPLES_DIR, out)
            write_file(dest, html)
            print("wrote %s (%d bytes, --site)" % (os.path.join("librewxr-site", "examples", out), os.path.getsize(dest)))
        rebuild_site_index_hero()


def main():
    parser = argparse.ArgumentParser(
        description="Build self-contained LibreWXR example pages from examples/src shells."
    )
    parser.add_argument(
        "--site",
        action="store_true",
        help="also write pinned API-base site variants to librewxr-site/examples/ "
             "and regenerate the shared-engine hero in librewxr-site/index.html",
    )
    args = parser.parse_args()
    build_pages(args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
